ARCHS = arm64 arm64e
INSTALL_TARGET_PROCESSES = Music
GO_EASY_ON_ME = YES

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = RoundMusicBar

RoundMusicBar_FILES = Tweak.x
RoundMusicBar_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
